name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
#      - uses: actions/setup-go@v1

      - name: Snyk monitor
        run: |
          snyk test --org=${{ secrets.SNYK_ORG }}
          snyk iac test --org=${{ secrets.SNYK_ORG }}
          snyk code test . --org=${{ secrets.SNYK_ORG }} 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
